# Generated by Django 3.2.15 on 2023-03-08 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_APP', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Address',
            new_name='address',
        ),
    ]
