# Generated by Django 4.1.5 on 2023-03-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_APP', '0004_rename_address_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
